// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABneX0ZpOgQiDi5Hbf0VoFld7u4mfoAyM',
    appId: '1:730244009596:web:bb42f5d5b90371272383f9',
    messagingSenderId: '730244009596',
    projectId: 'koyama-sushi-app',
    authDomain: 'koyama-sushi-app.firebaseapp.com',
    storageBucket: 'koyama-sushi-app.firebasestorage.app',
    measurementId: 'G-98V5K2LX8K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnNUE0njZX7ZjCbyXPce7x_kQ9QI5oegQ',
    appId: '1:730244009596:android:83fe4c65ccd45b8e2383f9',
    messagingSenderId: '730244009596',
    projectId: 'koyama-sushi-app',
    storageBucket: 'koyama-sushi-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFlCFEie6tirDDb9PjeSPcIby-Ql7m7Ao',
    appId: '1:730244009596:ios:080f63f2345365b72383f9',
    messagingSenderId: '730244009596',
    projectId: 'koyama-sushi-app',
    storageBucket: 'koyama-sushi-app.firebasestorage.app',
    iosBundleId: 'com.example.koyama',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFWw0zKyjkDCo8vAv8D8-EC5x1wItdQDY',
    appId: '1:242009344403:ios:2e06018aaa3bb0d17fc066',
    messagingSenderId: '242009344403',
    projectId: 'koyama-sushi-40f3f',
    storageBucket: 'koyama-sushi-40f3f.firebasestorage.app',
    iosBundleId: 'com.example.koyama',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBxaKP7a0yIysTYcukpSKc24hbtbsL8HU',
    appId: '1:242009344403:web:b75432bc6c20f3b17fc066',
    messagingSenderId: '242009344403',
    projectId: 'koyama-sushi-40f3f',
    authDomain: 'koyama-sushi-40f3f.firebaseapp.com',
    storageBucket: 'koyama-sushi-40f3f.firebasestorage.app',
    measurementId: 'G-WZZB4832LW',
  );
}