// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBxaKP7a0yIysTYcukpSKc24hbtbsL8HU',
    appId: '1:242009344403:web:d64688731cef0a187fc066',
    messagingSenderId: '242009344403',
    projectId: 'koyama-sushi-40f3f',
    authDomain: 'koyama-sushi-40f3f.firebaseapp.com',
    storageBucket: 'koyama-sushi-40f3f.firebasestorage.app',
    measurementId: 'G-H7E55TWKMC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAScsNorw-VhWnSW2I-LHpWfW7A0ZT16DE',
    appId: '1:242009344403:android:a0ad18663c02fa0c7fc066',
    messagingSenderId: '242009344403',
    projectId: 'koyama-sushi-40f3f',
    storageBucket: 'koyama-sushi-40f3f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFWw0zKyjkDCo8vAv8D8-EC5x1wItdQDY',
    appId: '1:242009344403:ios:2e06018aaa3bb0d17fc066',
    messagingSenderId: '242009344403',
    projectId: 'koyama-sushi-40f3f',
    storageBucket: 'koyama-sushi-40f3f.firebasestorage.app',
    iosBundleId: 'com.example.koyama',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFWw0zKyjkDCo8vAv8D8-EC5x1wItdQDY',
    appId: '1:242009344403:ios:2e06018aaa3bb0d17fc066',
    messagingSenderId: '242009344403',
    projectId: 'koyama-sushi-40f3f',
    storageBucket: 'koyama-sushi-40f3f.firebasestorage.app',
    iosBundleId: 'com.example.koyama',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBxaKP7a0yIysTYcukpSKc24hbtbsL8HU',
    appId: '1:242009344403:web:b75432bc6c20f3b17fc066',
    messagingSenderId: '242009344403',
    projectId: 'koyama-sushi-40f3f',
    authDomain: 'koyama-sushi-40f3f.firebaseapp.com',
    storageBucket: 'koyama-sushi-40f3f.firebasestorage.app',
    measurementId: 'G-WZZB4832LW',
  );
}
